name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  ci:
    name: ${{ matrix.ruby-version }} ${{ matrix.friendlyName }}-${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ruby-version:
          - "2.6"
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"
        arch:
          - x64
        includes:
          - os: ubuntu-latest
            friendlyName: Linux
          - os: macos-latest
            friendlyName: macOS
          - os: windows-latest
            friendlyName: Windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Ruby and install bundle
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Compile and run test
        run: bundle exec rake
